spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: dbc:postgresql://18.183.154.168:5432/excel
    username: postgres
    password: 123456
    maximum-pool-size: 30

